# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7
  

- script: |
    pip install databricks-cli
  displayName: 'Load Python Dependencies'
  
- task: CmdLine@2
  env:
    SOURCE_DATABRICKS_HOST: "${SOURCE_DB_HOST}"
    SOURCE_DATABRICKS_TOKEN: $(SOURCE_DB_TOKEN)
    TARGET_DATABRICKS_HOST: "${TARGET_DB_HOST}"
    TARGET_DATABRICKS_TOKEN: $(TARGET_DB_TOKEN)

  inputs:
    script: |
      python JobMigration.py $SOURCE_DATABRICKS_HOST $SOURCE_DATABRICKS_TOKEN $TARGET_DATABRICKS_HOST $TARGET_DATABRICKS_TOKEN
  displayName: 'Promote Jobs'